name: CI
on:
  push:
    branches:
      - master
    tags:
      - "*"
      - "**"
      - v*

  workflow_dispatch:

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.OWNER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: mtand
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: get docker tag
        id: git
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

          if [ "${GITHUB_REF#refs/heads/}" == "master" ]; then
            echo ::set-output name=DOCKER_TAG::latest
          else
            echo ::set-output name=DOCKER_TAG::${GITHUB_REF#refs/tags/}
          fi
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mtand/synapse:${{ steps.git.outputs.DOCKER_TAG }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Extract tag
        run: |
          set -e -x
          TAG=$(grep -Po 'synapse:\K(v.*)' Dockerfile)
          git tag $TAG || echo "Existing tag"
          git push origin $TAG || echo "tag exists"
