name: CI
on:
  push:
    branches:
      - master
    tags:
      - "*"
      - "**"
      - v*

  workflow_dispatch:

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.OWNER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.4.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get docker tag
        id: git
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

          if [ "${GITHUB_REF#refs/heads/}" == "master" ]; then
            echo ::set-output name=DOCKER_TAG::latest
          else
            echo ::set-output name=DOCKER_TAG::${GITHUB_REF#refs/tags/}
          fi
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

          tags: ghcr.io/mtandersson/synapse:${{ steps.git.outputs.DOCKER_TAG }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Extract tag
        run: |
          set -e -x
          TAG=$(grep -Po 'synapse:\K(v.*)' Dockerfile)
          git tag $TAG || echo "Existing tag"
          git push origin $TAG || echo "tag exists"
